### ISSUE TITLE
0.1.x: xmlns attribute eaten?

### ISSUE THREAD

**Issue by michael-brade** [svgdotjs/svgdom#68]
Sorry, one and a half more issues :-D

I have lots of unit tests and when switching to svgdom 0.1.8 I see that the following elements
```
<math xmlns="http://www.w3.org/1998/Math/MathML">
<svg xmlns="http://www.w3.org/2000/svg" width=...>
```
turn to
```
<math>
<svg width=...>
```
So the `xmlns` attribute disappears.

Also, the half-issue ;-), only when KaTeX is used, all the `style` attributes get spaces and the final style rule gets an `;`. All my other test cases don't change. I don't care much but maybe it's something you are interested in :grin:

**Comment by Fuzzyma** [comment]
I adapted the output of the style so it reflects the current browser behavior.
Thats why it changed. I am not sure what KaTeX is so I cannot help with that ^^.

The xmlns attribute dissappears? Well thats new. Can you give me example code?

**Comment by michael-brade** [comment]
Ok, will have to dig deeper then. Hang on...

**Comment by michael-brade** [comment]
I have to admit, I am not good with namespaces and serialization. It seems to me that the old svgdom included namespace attributes in `outerHTML` and `innerHTML`. The current one doesn't anymore, which is also what the browsers do. So to serialize a document properly, in the browser I would do:
```
var s = new XMLSerializer()
s.serializeToString(node)
```
However, there is no `XMLSerializer` in svgdom, so I had to rely on `innerHTML` and `outerHTML`. I now switched to https://www.npmjs.com/package/w3c-xmlserializer. But now I got (some of) the SVG namespaces duplicated :confounded: why is this so hard...

Now back to the style formatting: this was my fault :-D
```
let div = document.createElement("div")

div.style.marginRight = "4em"
div.style.marginLeft = "4em"

console.log("CREATE formatted: ", div.outerHTML)

div.setAttribute("style", "width:100px;height:4px")

console.log("CREATE unformatted: ", div.outerHTML)
```
`setAttribute()` just sets the style without any changes by svgdom. Again, this is also what the browser does, so I am sorry for the noise.

**Comment by Fuzzyma** [comment]
> However, there is no XMLSerializer in svgdom

jaja its on the list :D

My actual question was how you create the markup which you try to export.
Because when I do a simple:

```js
const canvas = SVG().size(100, 50)
console.log(canvas.svg())
```

I get the correct output:

```html
<svg xmlns="http://www.w3.org/2000/svg" version="1.1" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:svgjs="http://svgjs.com/svgjs" width="100" height="50"></svg>
```

However, svg.js is explicitely setting those namespaces on the element.
outerHTML as per spec ony gives you whats in the markup. So if you didnt actually set the xmlns attribute, it is just not there.

If you, on the other hand, created your dom via import, the parser might be missing it

**Comment by michael-brade** [comment]
> > However, there is no XMLSerializer in svgdom
> 
> jaja its on the list :D

yay!! :smile: 

> My actual question was how you create the markup which you try to export.
> [...]
> However, svg.js is explicitely setting those namespaces on the element.
> outerHTML as per spec ony gives you whats in the markup. So if you didnt actually set the xmlns attribute, it is just not there.

I see. It was just a simple
```js
document.createElementNS("http://www.w3.org/1998/Math/MathML", "math")
```

**Comment by Fuzzyma** [comment]
In that case an XML serializer would solve the problem. However, outerHTML is behaving correctly here

**Comment by michael-brade** [comment]
Ok, so I guess we can close this :-) Thanks!

**Comment by Fuzzyma** [comment]
Just as a quickfix you can set the attributes explicitely when you need them after export.
I realized that svg.js could just get rid of all the namespace declarations because they are not really needed because the elements are created with the NS-version which already tells the browser in which namespace the element is.
The namespace declarations are only important when the dom is converted to actual text (or xml) because on import all nodes have to be imported in the correct namespace again

**Comment by Fuzzyma** [comment]
(as a sidenote: svg.js is actually epxorting svgs wrong because we use outerHTML - aiaiai)

**Comment by michael-brade** [comment]
BTW, maybe you don't need to write an XMLSerializer, the one I mentioned above does its work pretty well. But what I didn't find is a HTMLSerializer that outputs valid HTML5 (*hint hint* :-D). So I am back to using outerHTML and don't care about namespaces in unit tests for now...

**Comment by Fuzzyma** [comment]
Well - but didnt it create duplicated namespaces?
The fact that this serializer works with svgdom means, that svgdom seems to be quite compatible with a real dom already :D

**Comment by michael-brade** [comment]
True :-)) But now I thought it might be because of the "namespace declarations" in svg.js that you mentioned above. I didn't investigate.... if you want me to, I'll try to find some time for it.

**Comment by Fuzzyma** [comment]
hmmm but they shouldnt get doubled, too...
yes pls investigate or give me some code so I can have a look ):)

**Comment by michael-brade** [comment]
Ok, now I would be ready again, but I see that you already found the right bug for `w3c-xmlserializer`. So I guess we'll just have to wait :-)

**Comment by Fuzzyma** [comment]
haha yes, but I dont even know it is a bug... well it certainly is because the same attribute should not appear twice. But it follows the spec behavior. I think it can be solved by just creating the xmlns attribute in the xmlns namespace (it has its own). However, I am not sure if I can make this change in svg.js without some browser complaining about it :/
